replicaCount: 1


image:
  repository: srikanthgorrepatig/node-demo
  tag: v1.0.0
  pullPolicy: IfNotPresent


service:
type: ClusterIP
port: 3000


ingress:
  enabled: true
  hostname: node-demo.local

  tls:
    enabled: true
    secretName: node-demo-tls
