apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-demo-deployment
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-demo
  template:
    metadata:
      labels:
        app: node-demo
    spec:
      containers:
        - name: node-demo
          image: srikanthawsos/node-docker-demo:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
