apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-demo-ingress
  namespace: demo-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - node-demo.local
    secretName: node-demo-tls
  rules:
  - host: node-demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-demo-service
            port:
              number: 80
